version: 0.1

environment_variables:
  plaintext:
    STAGE: "test"

phases:
  install:
    commands:
      - pip install virtualenv
      - virtualenv venv && . ./venv/bin/activate && pip install -r requirements.txt
  pre_build:
    commands:
      - aws s3 cp s3://$S3_BUCKET/sql-app/zappa_settings.json .
  build:
    commands:
      - . ./venv/bin/activate && zappa update $STAGE
  post_build:
    commands:
      - rm zappa_settings.json
      - rm -rf ./venv
